ALTER TABLE orders ADD COLUMN IF NOT EXISTS fabric_usage_mb NUMERIC(6,2) DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fabric_usage_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fabric_usage_updated_by UUID REFERENCES auth.users(id) DEFAULT NULL;