
INSERT INTO workstations (code, name, icon, sort_order, active) 
VALUES ('kierownik', 'Kierownik produkcji', '👔', 100, true)
ON CONFLICT DO NOTHING;

DELETE FROM cheatsheet_sections;

INSERT INTO cheatsheet_sections (workstation_id, section_name, renderer_type, data_source, columns, filters, renderer_config, sort_order, show_specs, notes) VALUES
((SELECT id FROM workstations WHERE code = 'magazyn'), 'Sprężyny', 'springs_table', 'products:seat', '[{"key":"model_name","label":"Model"},{"key":"code","label":"Kod"},{"key":"spring","label":"Sprężyna"}]', '{"category":"seat"}', '{"highlight_exceptions":true}', 10, false, 'Modele siedzisk z typem sprężyny. Wyjątki podświetlone na czerwono.'),
((SELECT id FROM workstations WHERE code = 'magazyn'), 'Siedziska', 'seats_detail', 'products:seat', '[]', '{"category":"seat"}', '{"show_foams":true,"foam_component":"siedzisko"}', 20, true, NULL),
((SELECT id FROM workstations WHERE code = 'magazyn'), 'Oparcia', 'backrests_detail', 'products:backrest', '[]', '{"category":"backrest"}', '{"show_foams":true}', 30, true, NULL),
((SELECT id FROM workstations WHERE code = 'magazyn'), 'Boczki', 'generic_table', 'products:side', '[{"key":"code","label":"Kod","mono":true},{"key":"name","label":"Nazwa"},{"key":"properties.frame","label":"Stelaż"}]', '{"category":"side"}', '{}', 40, false, NULL),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Legenda wykończeń', 'finish_legend', 'products:finish', '[]', '{"category":"finish"}', '{}', 10, false, NULL),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Pułapki — PRZECZYTAJ UWAŻNIE!', 'finish_warnings', 'products:seat', '[]', '{"category":"seat"}', '{}', 20, false, 'Wykończenie poduszek / jaśków / wałków = DZIEDZICZONE od siedziska!'),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Wykończenia siedzisk', 'finishes_table', 'products:seat', '[{"key":"code","label":"Kod","mono":true},{"key":"properties.model_name","label":"Model"},{"key":"allowed_finishes","label":"Dozwolone"},{"key":"default_finish","label":"Domyślne","bold":true}]', '{"category":"seat"}', '{}', 30, false, NULL),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Wykończenia boczków', 'finishes_table', 'products:side', '[{"key":"code","label":"Kod","mono":true},{"key":"name","label":"Nazwa"},{"key":"allowed_finishes","label":"Dozwolone"},{"key":"default_finish","label":"Domyślne","bold":true}]', '{"category":"side"}', '{}', 40, false, NULL),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Wykończenia oparć', 'finishes_table', 'products:backrest', '[{"key":"code","label":"Kod","mono":true},{"key":"allowed_finishes","label":"Dozwolone"},{"key":"default_finish","label":"Domyślne","bold":true}]', '{"category":"backrest"}', '{}', 50, false, NULL),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Warianty szycia oparcia', 'sewing_variants', 'sewing_variants', '[{"key":"variant_name","label":"Wariant","bold":true},{"key":"models","label":"Modele"},{"key":"description","label":"Opis"}]', '{"component_type":"backrest"}', '{"style":"warning_box"}', 60, false, 'Różne modele mają różne rysunki oparcia. Sprawdź model przed krojem!'),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Poduszki per siedzisko', 'pillow_mapping', 'product_relations:seat_pillow_map', '[{"key":"seat_code","label":"Siedzisko","mono":true},{"key":"pillow_code","label":"Poduszka"},{"key":"pillow_finish","label":"Wykończenie"}]', '{"relation_type":"seat_pillow_map"}', '{}', 70, false, NULL),
((SELECT id FROM workstations WHERE code = 'krojownia'), 'Tkaniny', 'fabrics_table', 'products:fabric', '[{"key":"code","label":"Kod","mono":true,"bold":true},{"key":"name","label":"Nazwa"},{"key":"properties.price_group","label":"Grupa"},{"key":"colors","label":"Kolory"}]', '{"category":"fabric"}', '{}', 80, false, NULL),
((SELECT id FROM workstations WHERE code = 'nozki'), 'Kompletacja nóżek', 'leg_completion', 'mixed', '[]', '{}', '{}', 10, false, NULL),
((SELECT id FROM workstations WHERE code = 'nozki'), 'Typy nóżek', 'generic_table', 'products:leg', '[{"key":"code","label":"Kod","mono":true,"bold":true},{"key":"name","label":"Nazwa"},{"key":"properties.material","label":"Materiał"},{"key":"colors","label":"Kolory","format":"colors"}]', '{"category":"leg","is_global":true}', '{}', 20, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Legenda wykończeń', 'finish_legend', 'products:finish', '[]', '{"category":"finish"}', '{}', 10, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Konfiguracja', 'series_config_summary', 'series_config', '[]', '{}', '{}', 20, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Skrzynie', 'generic_table', 'products:chest', '[{"key":"code","label":"Kod","mono":true},{"key":"name","label":"Nazwa"},{"key":"properties.leg_height_cm","label":"Wys. nóżek","suffix":"cm"}]', '{"category":"chest","is_global":true}', '{"filter_by_series_config":"available_chests"}', 30, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Siedziska sofa', 'seats_compact_table', 'products:seat', '[{"key":"code","label":"Kod","mono":true},{"key":"properties.model_name","label":"Model"},{"key":"properties.seat_type","label":"Typ"},{"key":"properties.frame","label":"Stelaż"},{"key":"properties.frame_modification","label":"Mod."},{"key":"spring","label":"Sprężyna","bold":true},{"key":"foams","label":"Pianka"},{"key":"properties.center_strip","label":"Pasek","format":"boolean"},{"key":"allowed_finishes","label":"Wykoń.","format":"join"}]', '{"category":"seat"}', '{"show_spring_exceptions":true,"show_foams_inline":true,"foam_component":"siedzisko"}', 40, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Oparcia', 'backrests_compact_table', 'products:backrest', '[{"key":"code","label":"Kod","mono":true},{"key":"properties.height_cm","label":"Wys."},{"key":"properties.frame","label":"Stelaż"},{"key":"foams","label":"Pianka"},{"key":"properties.top","label":"Góra"},{"key":"allowed_finishes","label":"Wykoń.","format":"join"}]', '{"category":"backrest"}', '{"show_foams_inline":true}', 50, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Boczki', 'generic_table', 'products:side', '[{"key":"code","label":"Kod","mono":true},{"key":"name","label":"Nazwa"},{"key":"properties.frame","label":"Stelaż"},{"key":"allowed_finishes","label":"Wykoń.","format":"join"}]', '{"category":"side"}', '{}', 60, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Nóżki', 'generic_table', 'products:leg', '[{"key":"code","label":"Kod","mono":true},{"key":"name","label":"Nazwa"},{"key":"properties.material","label":"Materiał"},{"key":"colors","label":"Kolory","format":"colors"}]', '{"category":"leg","is_global":true}', '{}', 70, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Automaty', 'automats_table', 'product_relations:automat_config', '[{"key":"automat_code","label":"Kod","mono":true},{"key":"automat_name","label":"Nazwa"},{"key":"automat_type","label":"Typ"},{"key":"seat_legs","label":"Nóżki siedziska"}]', '{"relation_type":"automat_config"}', '{}', 80, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Pufa', 'generic_table', 'products:seat_pufa', '[{"key":"code","label":"Kod","mono":true},{"key":"properties.front_back","label":"Przód/tył"},{"key":"properties.sides","label":"Boki"},{"key":"properties.base_foam","label":"Pianka bazy"},{"key":"properties.box_height","label":"Wys. skrzynki"}]', '{"category":"seat_pufa"}', '{}', 90, false, NULL),
((SELECT id FROM workstations WHERE code = 'kierownik'), 'Tkaniny', 'fabrics_table', 'products:fabric', '[{"key":"code","label":"Kod","mono":true,"bold":true},{"key":"name","label":"Nazwa"},{"key":"properties.price_group","label":"Grupa"},{"key":"colors","label":"Kolory"}]', '{"category":"fabric"}', '{}', 100, false, NULL);
